require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "spec/dummy/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Layout/LineLength:
  Max: 120
