require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/migrate/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "stubs/**/*"

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
    - "lib/tasks/**/*"
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 50
  Exclude:
    - "lib/escalated/services/hook_registry.rb"

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 35

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ClassLength:
  Max: 350

Metrics/ModuleLength:
  Max: 350

Metrics/ParameterLists:
  Max: 6

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/FormatStringToken:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Rails/SkipsModelValidations:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/WhereNotWithMultipleConditions:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/ContextWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/RepeatedExample:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
