source 'https://rubygems.org'

ruby '>= 3.1'

gem 'rails', '~> 7.1'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'bootsnap', require: false
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'escalated', path: '/package'
gem 'inertia_rails', '~> 3.0'
gem 'pundit'

group :development do
  gem 'web-console'
end
